version: "3"

services:

  db_test:
    image: postgres:11
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: -p 5433

  web:
    build: .
    command: bash -c "poetry run pytest ."
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db_test
