"""add tags, is_admin, is_moderator to user

Revision ID: 0ef3cdf64010
Revises: 1344d5d37d86
Create Date: 2022-04-05 14:40:02.013020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef3cdf64010'
down_revision = '1344d5d37d86'
branch_labels = None
depends_on = None


def upgrade():
    # tags
    op.add_column(
        'user',
        sa.Column(
            'tags',
            sa.ARRAY(sa.String(length=15)),
            server_default='{}', nullable=True
        )
    )
    op.execute("UPDATE \"user\" SET tags = '{}'")
    op.alter_column('user', 'tags', nullable=False)

    # is_admin
    op.add_column(
        'user',
        sa.Column(
            'is_admin',
            sa.Boolean(),
            nullable=True
        )
    )
    op.execute("UPDATE \"user\" SET is_admin = false")
    op.alter_column('user', 'is_admin', nullable=False)

    # is_moderator
    op.add_column(
        'user',
        sa.Column(
            'is_moderator',
            sa.Boolean(),
            nullable=True
        )
    )
    op.execute("UPDATE \"user\" SET is_moderator = false")
    op.alter_column('user', 'is_moderator', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_moderator')
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'tags')
    # ### end Alembic commands ###
