"""delete index=True

Revision ID: 127959d37051
Revises: 14af79e286cc
Create Date: 2022-04-07 01:16:06.917841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127959d37051'
down_revision = '14af79e286cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_place_description_key', 'event', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('event_place_description_key', 'event', ['place_description'])
    # ### end Alembic commands ###
