"""delete index=True

Revision ID: 14af79e286cc
Revises: a33aef10a7dd
Create Date: 2022-04-07 01:14:19.300407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14af79e286cc'
down_revision = 'a33aef10a7dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_description_key', 'event', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('event_description_key', 'event', ['description'])
    # ### end Alembic commands ###
