"""cascade delete for UserSubscription

Revision ID: 39b5a0df3498
Revises: fa2784a17577
Create Date: 2022-04-09 17:46:11.298794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b5a0df3498'
down_revision = 'fa2784a17577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('usersubscription_follower_id_fkey', 'usersubscription', type_='foreignkey')
    op.drop_constraint('usersubscription_user_id_fkey', 'usersubscription', type_='foreignkey')
    op.create_foreign_key(None, 'usersubscription', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'usersubscription', 'user', ['follower_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usersubscription', type_='foreignkey')
    op.drop_constraint(None, 'usersubscription', type_='foreignkey')
    op.create_foreign_key('usersubscription_user_id_fkey', 'usersubscription', 'user', ['user_id'], ['id'])
    op.create_foreign_key('usersubscription_follower_id_fkey', 'usersubscription', 'user', ['follower_id'], ['id'])
    # ### end Alembic commands ###
