"""fix size of strings

Revision ID: 54e9832835f7
Revises: b64c3b4ede90
Create Date: 2022-05-29 22:28:56.924579

"""
import sqlalchemy as sa
import sqlalchemy_utc
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54e9832835f7'
down_revision = 'b64c3b4ede90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE \"event\" SET title=left(title, 50)")
    op.execute("UPDATE \"event\" SET description=left(description, 255)")
    op.execute(
        "UPDATE \"event\" SET place_description=left(place_description, 50)")
    op.execute("UPDATE \"organization\" SET title=left(title, 50)")
    op.execute("UPDATE \"organization\" SET description=left(description, 255)")
    op.alter_column('event', 'title',
                    existing_type=sa.VARCHAR(length=100),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.alter_column('event', 'description',
                    existing_type=sa.VARCHAR(length=1000),
                    type_=sa.String(length=255),
                    existing_nullable=False)
    op.alter_column('event', 'date_begin',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True),
                    existing_nullable=False)
    op.alter_column('event', 'date_end',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True),
                    existing_nullable=False)
    op.alter_column('event', 'place_description',
                    existing_type=sa.VARCHAR(length=100),
                    type_=sa.String(length=50),
                    existing_nullable=False)
    op.alter_column('event', 'tags',
                    existing_type=postgresql.ARRAY(sa.VARCHAR(length=15)),
                    type_=postgresql.ARRAY(sa.String(length=30)),
                    existing_nullable=True,
                    existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('organization', 'title',
                    existing_type=sa.VARCHAR(length=100),
                    type_=sa.String(length=50),
                    existing_nullable=False)
    op.alter_column('organization', 'description',
                    existing_type=sa.VARCHAR(length=250),
                    type_=sa.String(length=255),
                    existing_nullable=False)
    op.alter_column('user', 'tags',
                    existing_type=postgresql.ARRAY(sa.VARCHAR(length=15)),
                    type_=sa.ARRAY(sa.String(length=30)),
                    existing_nullable=True,
                    existing_server_default=sa.text("'{}'::character varying[]"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'tags',
                    existing_type=sa.ARRAY(sa.String(length=30)),
                    type_=postgresql.ARRAY(sa.VARCHAR(length=15)),
                    existing_nullable=True,
                    existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('organization', 'description',
                    existing_type=sa.String(length=255),
                    type_=sa.VARCHAR(length=250),
                    existing_nullable=False)
    op.alter_column('organization', 'title',
                    existing_type=sa.String(length=50),
                    type_=sa.VARCHAR(length=100),
                    existing_nullable=False)
    op.alter_column('event', 'tags',
                    existing_type=postgresql.ARRAY(sa.String(length=30)),
                    type_=postgresql.ARRAY(sa.VARCHAR(length=15)),
                    existing_nullable=True,
                    existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('event', 'place_description',
                    existing_type=sa.String(length=50),
                    type_=sa.VARCHAR(length=100),
                    existing_nullable=False)
    op.alter_column('event', 'date_end',
                    existing_type=sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=False)
    op.alter_column('event', 'date_begin',
                    existing_type=sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=False)
    op.alter_column('event', 'description',
                    existing_type=sa.String(length=255),
                    type_=sa.VARCHAR(length=1000),
                    existing_nullable=False)
    op.alter_column('event', 'title',
                    existing_type=sa.String(length=50),
                    type_=sa.VARCHAR(length=100),
                    existing_nullable=True)
    # ### end Alembic commands ###
