"""in event, url is not required

Revision ID: 6c0a53b9fb26
Revises: efe72bc0154b
Create Date: 2022-04-20 18:08:49.432944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0a53b9fb26'
down_revision = 'efe72bc0154b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'url',
               existing_type=sa.VARCHAR(length=2083),
               nullable=True)
    op.execute("UPDATE \"event\" SET url=null")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE \"event\" SET url='https://google.com/'")
    op.alter_column('event', 'url',
               existing_type=sa.VARCHAR(length=2083),
               nullable=False)
    # ### end Alembic commands ###
