"""delete index=True

Revision ID: a33aef10a7dd
Revises: 466f5ee69dc4
Create Date: 2022-04-07 01:12:07.275586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33aef10a7dd'
down_revision = '466f5ee69dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_date_begin', table_name='event')
    op.drop_index('ix_event_date_end', table_name='event')
    op.drop_index('ix_event_title', table_name='event')
    op.drop_index('ix_user_name', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    op.create_index('ix_event_title', 'event', ['title'], unique=False)
    op.create_index('ix_event_date_end', 'event', ['date_end'], unique=False)
    op.create_index('ix_event_date_begin', 'event', ['date_begin'], unique=False)
    # ### end Alembic commands ###
