"""init event table, relation between event and user

Revision ID: aa1826abe1cc
Revises: 0ef3cdf64010
Create Date: 2022-04-05 16:07:35.697005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa1826abe1cc'
down_revision = '0ef3cdf64010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('date_begin', sa.DateTime(), nullable=False),
    sa.Column('date_end', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('place_description', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String(length=15)), server_default='{}', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_index(op.f('ix_event_date_begin'), 'event', ['date_begin'], unique=False)
    op.create_index(op.f('ix_event_date_end'), 'event', ['date_end'], unique=False)
    op.create_index(op.f('ix_event_id'), 'event', ['id'], unique=False)
    op.create_index(op.f('ix_event_place_description'), 'event', ['place_description'], unique=True)
    op.create_index(op.f('ix_event_title'), 'event', ['title'], unique=False)
    op.alter_column('user', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=15)),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=15)),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.drop_index(op.f('ix_event_title'), table_name='event')
    op.drop_index(op.f('ix_event_place_description'), table_name='event')
    op.drop_index(op.f('ix_event_id'), table_name='event')
    op.drop_index(op.f('ix_event_date_end'), table_name='event')
    op.drop_index(op.f('ix_event_date_begin'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
