"""add organization_id in event table

Revision ID: b12324e0d236
Revises: f7b8c438d7ba
Create Date: 2022-04-15 19:28:19.584155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b12324e0d236'
down_revision = 'f7b8c438d7ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event', 'organization', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'organization_id')
    # ### end Alembic commands ###
