"""add is_active in user table

Revision ID: b64c3b4ede90
Revises: f0a2f7ecdd72
Create Date: 2022-05-27 13:16:52.869425

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b64c3b4ede90'
down_revision = 'f0a2f7ecdd72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute("UPDATE \"user\" SET is_active = true")
    op.alter_column('user', 'is_active', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
