"""add url field for event

Revision ID: efe72bc0154b
Revises: c76de7afa966
Create Date: 2022-04-20 01:20:59.286418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe72bc0154b'
down_revision = 'c76de7afa966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'event', sa.Column('url', sa.String(length=2083),
                           nullable=True))
    op.execute("UPDATE \"event\" SET url='https://google.com/'")
    op.alter_column("event", "url", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'url')
    # ### end Alembic commands ###
