"""add image_uuid4 to user

Revision ID: f0a2f7ecdd72
Revises: 6c0a53b9fb26
Create Date: 2022-04-22 01:30:43.171825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a2f7ecdd72'
down_revision = '6c0a53b9fb26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_uuid4', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_uuid4')
    # ### end Alembic commands ###
