"""add is_owner to user_organization

Revision ID: f7b8c438d7ba
Revises: d89a16e88480
Create Date: 2022-04-13 21:27:08.062811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b8c438d7ba'
down_revision = 'd89a16e88480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userorganization', sa.Column('is_owner', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userorganization', 'is_owner')
    # ### end Alembic commands ###
